# local pg login
[local_pg]
host = "localhost"
port = "5432"
user = ""
password = ""
ssl = "disable"

# cloud pg login
[cloud_pg]
host = ""
port = "5432"
user = ""
password = ""
ssl = "require"

# local pg login
[local_mssql]
host = "localhost"
server = "SQLHOST"
user = ""
password = ""

# cloud pg login
[local_mysql]
host = ""
user = ""
password = ""